[types.crates]
# need to add this because it isn't automatically added by clorinde since there is no
# date type in the schema
chrono = "0.4.40"

postgres_range = { version = "0.11.1", features = ["with-chrono-0_4"] }

[types.mapping]
"pg_catalog.tstzrange" = "postgres_range::Range<chrono::DateTime<chrono::FixedOffset>>"
